- name: Haproxy
  hosts: haproxy
  become: yes
  roles:
    - keepalive
    - haproxy

- name: Kubernetes master
  hosts: kube_master, kube_worker
  become: yes
  roles:
    - cri-o
    - kubernetes-install

- name: Kubernetes boot
  hosts: kube_master
  become: yes
  roles:
    - kubernetes-controller

- name: Kubernetes controller join
  hosts: kube_master, !kube_master[0]
  become: yes
  roles:
    - kubernetes-controller-join

- name: Kubernetes worker
  hosts: kube_worker
  become: yes
  roles:
    - kubernetes-worker
