- name: Haproxy
  hosts: haproxy
  become: yes
  vars:
    - VIP: 10.200.110.200
  roles:
    - keepalive
    - haproxy

- name: Kubernetes master
  hosts: kube_master, kube_worker
  become: yes
  vars:
    - OS: Debian_11
    - CRIO_VERSION: 1.23
  roles:
    - cri-o
    - kubernetes-install

- name: Kubernetes boot
  hosts: kube_master
  become: yes
  vars:
    - KUBE_DNS: silk-kube-master.global.local
    - VIP: 10.200.110.200
    - POD_CIDER: 172.16.0.0/16
  roles:
    - kubernetes-controller

- name: Kubernetes controller join
  hosts: kube_master, !kube_master[0]
  become: yes
  roles:
    - kubernetes-controller-join

- name: Kubernetes worker
  hosts: kube_worker
  become: yes
  roles:
    - kubernetes-worker