#- name: Haproxy
#  hosts: haproxy
#  become: yes
#  vars:
#    - VIP: 10.200.50.200
#    - KEEP_PASSWD: Password1!
#  roles:
#    - keepalive
#    - haproxy

- name: Kubernetes master 
  hosts: kube-master
  become: yes
  roles:
    - containerd
    - kubernetes-install

- name: Kubernetes master boot
  hosts: kube-master
  become: yes
  vars:
    - VIP: 10.200.80.200
    - POD_CIDER: 172.16.0.0/16
  roles:
    - kubernetes-master