---
- name: Create containerd.conf 
  file:
    path: /etc/modules-load.d/containerd.conf
    state: touch

- name: add line to containerd.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - overlay
    - br_netfilter

- name: modprod
  modprobe:
    name: "{{ item }}"
  with_items: 
    - overlay
    - br_netfilter

- name: Create containerd.conf 
  file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: touch

- name: add line to containerd.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.ipv4.ip_forward                 = 1
    - net.bridge.bridge-nf-call-ip6tables = 1

- name: sysctl
  become: true
  command: sysctl --system

- name: Disable SWAP (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install recomendet
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates

- name: add Kubernetes apt-key for APT repository
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install Kubernetes packes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet 
    - kubeadm 
    - kubectl

- name: Hold kubernetes
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet 
    - kubeadm 
    - kubectl