---
- include_vars: ../../vars.yaml

- name: Install Packet
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg2
  when: CNI == "cri-o"

- name: Create /etc/modules-load.d/crio.conf
  lineinfile:
    path: /etc/modules-load.d/crio.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - overlay
    - br_netfilter
  when: CNI == "cri-o"

- name: Create /etc/sysctl.d/99-kubernetes-cri.conf
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.ipv4.ip_forward                 = 1
    - net.bridge.bridge-nf-call-ip6tables = 1
  when: CNI == "cri-o"

- name: modprode
  command: "{{ item }}"
  with_items:
    - modprobe overlay
    - modprobe br_netfilter
    - sudo sysctl --system
  when: CNI == "cri-o"

- name: Create /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  copy:
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    content: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{vars.OS}}/ /
  when: CNI == "cri-o"

- name: Create /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{vars.OS}}.list
  copy:
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{vars.OS}}.list
    content: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{vars.CRIO_VERSION}}/{{vars.OS}}/ /
  when: CNI == "cri-o"

- name: CRI-O add pgp
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{vars.CRIO_VERSION}}/{{vars.OS}}/Release.key
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{vars.OS}}/Release.key
  when: CNI == "cri-o"

- name: Update apt cache
  apt:
    update_cache: yes
  when: CNI == "cri-o"

- name: Install CRI-O
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - cri-o 
    - cri-o-runc
    - cri-tools
  when: CNI == "cri-o"

- name: Start cri-o
  service:
    name: crio
    daemon_reload: true
    state: started
  when: CNI == "cri-o"

- name: Enable cri-o
  service:
    name: crio
    enabled: yes
  when: CNI == "cri-o"