---
- include_vars: ../../vars.yaml

- name: Install gnupg2
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - gnupg2

- name: Create /etc/modules-load.d/crio.conf
  ansible.builtin.copy: 
    dest: /etc/modules-load.d/crio.conf
    content: |
      overlay
      br_netfilter

- name: Create /etc/sysctl.d/99-kubernetes-cri.conf
  ansible.builtin.copy: 
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: modprode
  command: "{{ item }}"
  with_items:
    - modprobe overlay
    - modprobe br_netfilter
    - sudo sysctl --system

- name: Create /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    content: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{vars.OS}}/ /

- name: Create /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{vars.OS}}.list
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{vars.OS}}.list
    content: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{vars.CRIO_VERSION}}/{{vars.OS}}/ /

- name: CRI-O add gpg
  shell: "{{ item }}"
  with_items:
    - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{vars.CRIO_VERSION}}/{{vars.OS}}/Release.key | apt-key add -
    - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{vars.OS}}/Release.key | apt-key add -

#- name: CRI-O add pgp1
#  ansible.builtin.apt_key:
#    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{vars.CRIO_VERSION}}/{{vars.OS}}/Release.key
#    state: present

#- name: CRI-O add pgp2
#  ansible.builtin.apt_key:
#    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{vars.OS}}/Release.key
#    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install CRI-O
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  with_items:
    - cri-o 
    - cri-o-runc
    - cri-tools

- name: Start cri-o
  ansible.builtin.service:
    name: crio
    daemon_reload: true
    state: started

- name: Enable cri-o
  ansible.builtin.service:
    name: crio
    enabled: yes