---
- name: Reboot
  ansible.builtin.reboot:

- name: Bootstrep
  command:  sudo kubeadm init --control-plane-endpoint "{{ KUBE_DNS }}:6443" --upload-certs --pod-network-cidr="{{POD_CIDER}}"
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Create config to kubectl
  command: "{{ item }}"
  with_items:
    - sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Get join command to control plane
  copy: src=./files/kubeadm_controller.sh dest=/root/kubeadm_controller.sh mode=0777
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Execut /tmp/kubeadm_controller.sh
  command: sh /root/kubeadm_controller.sh
  register: kube_join_controller
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Print kubeadm
  debug:
    var: kube_join_controller.stdout_lines

- name: Write kubeadm controller join command to file
  copy:
    content: "{{ kube_join_controller.stdout }}"
    dest: /root/kubeadm-join-command.sh
    owner: root
    group: root
    mode: '0777'
  delegate_to: "{{ item }}"
  when: inventory_hostname != groups['kube_master'][0]
  with_items: "{{ groups['kube_master'] }}"

- name: Get join command to worker
  copy: src=./files/kubeadm_worker.sh dest=/root/kubeadm_worker.sh mode=0777
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Execut /tmp/kubeadm_worker.sh
  command: sh /root/kubeadm_worker.sh
  register: kube_join_worker
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Write kubeadm worker join command
  debug:
    var: kube_join_worker.stdout_lines

- name: Write kubeadm worker join command
  copy:
    content: "{{ kube_join_worker.stdout }}"
    dest: /tmp/kubeadm-join-worker.sh
    owner: root
    group: root
    mode: '0777'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube_worker'] }}"


#- name: Join worker
#  command: sh /tmp/kubeadm-join-worker.sh
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['kube_worker'] }}"
#  ignore_errors: true