---
- include_vars: ../../vars.yaml

- name: Bootstrep kubernetes
  command:  sudo kubeadm init --control-plane-endpoint "{{ vars.KUBE_DNS }}:6443" --upload-certs
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Create dir /root/.kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Copy admin.conf to .kube
  command: sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Copy kubernetes_controller.sh file to first master 
  copy: src=./files/kubeadm_controller.sh dest=/root/kubeadm_controller.sh mode=0777
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Execut kubeadm controller
  command: sh /root/kubeadm_controller.sh
  register: kube_join_controller
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Write kube_join_controller output to /root/kube-join-command.sh 
  copy:
    content: "{{ kube_join_controller.stdout }}"
    dest: /root/kubeadm-join-command.sh
    owner: root
    group: root
    mode: '0777'
  delegate_to: "{{ item }}"
  when: inventory_hostname != groups['kube_master'][0]
  with_items: "{{ groups['kube_master'] }}"

- name: Copy kubernetes_worker.sh to first master node  
  copy: src=./files/kubeadm_worker.sh dest=/root/kubeadm_worker.sh mode=0777
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Execut /root/kubeadm_worker.sh
  command: sh /root/kubeadm_worker.sh
  register: kube_join_worker
  delegate_to: "{{ groups.kube_master[0] }}"
  run_once: true

- name: Write kubeadm worker join command to /tmp/kubeadm-join-worker.sh on all worker
  copy:
    content: "{{ kube_join_worker.stdout }}"
    dest: /tmp/kubeadm-join-worker.sh
    owner: root
    group: root
    mode: '0777'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube_worker'] }}"

- name: Remove kubeadm files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/kubeadm_controller.sh
    - /root/kubeadm-join-command.sh
    - /root/kubeadm_worker.sh
  delegate_to: "{{ groups.kube_master[0] }}"