---
- name: Join control plane nodes
  command: sh /root/kubeadm-join-command.sh

- name: Remove kubeadm files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/kubeadm_controller.sh
    - /root/kubeadm-join-command.sh
    - /root/kubeadm_worker.sh