---
- name: Create containerd.conf 
  file:
    path: /etc/modules-load.d/containerd.conf
    state: touch

- name: add line to containerd.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - overlay
    - br_netfilter

- name: modprod
  modprobe:
    name: "{{ item }}"
  with_items: 
    - overlay
    - br_netfilter

- name: Create containerd.conf 
  file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: touch

- name: add line to containerd.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.ipv4.ip_forward                 = 1
    - net.bridge.bridge-nf-call-ip6tables = 1

#- name: config /etc/sysctl.d/99-kubernetes-cri.conf
#  command: | 
#    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
#    net.bridge.bridge-nf-call-iptables  = 1
#    net.ipv4.ip_forward                 = 1
#    net.bridge.bridge-nf-call-ip6tables = 1
#    EOF

- name: sysctl
  become: true
  command: sysctl --system

- name: Disable SWAP (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install recomendet
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates

- name: Add Kubernetes gpg
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add kubernetes repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes packes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet 
    - kubeadm 
    - kubectl

- name: Hold kubernetes
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet 
    - kubeadm 
    - kubectl

- name: Bootstrap kubernetes cluster
  command: sudo kubeadm init --pod-network-cidr="{{ POD_CIDER }}" --apiserver-advertise-address="{{ VIP }}"
  delegate_to: kubernetes-master[0]
#  register: kubernetes-token
#- debug:
#    msg: '{{ bob.stdout_lines | select("search", "systemd") | list }}'

- name: Get Kubernetes config
  command: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - sudo chown $(id -u):$(id -g) $HOME/.kube/config
  delegate_to: kubernetes-master[0]

- name: Get kubernetes token
  command: 