---
- name: "run on that_one_host host"
  command: sudo kubeadm init --pod-network-cidr="{{ POD_CIDER }}" --apiserver-advertise-address="{{ VIP }}"
  delegate_to: “{{groups[‘kube-master’][0]}}“
  run_once: true

#- name: Include cinder-compute role
#  include_role:
#    name: kubernetes-master-boot
#    apply:
#      delegate_to: kubernetes-master[0] #"{{ item }}"
#  with_items: "{{ groups['kubernetes-master[0]'] }}"
