---
- include_vars: ../../vars.yaml

- name: Create pass 
  set_fact:
    keep_pass: "{{ lookup('ansible.builtin.password', '/tmp/passwordfile chars=ascii_letters') }}"
  run_once: true

- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Config Keekalived
  template:
    src: ../templates/keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root

- name: Enable Keekalived
  service:
    name: keepalived
    enabled: yes

- name: Restart Keekalived
  service:
    name: keepalived
    state: reloaded
