---
- name: Install packes
  apt: 
    name: "{{ item }}"
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update repository cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install containerd.io
  apt:
    name: containerd.io
    state: present

- name: Creates directory
  file:
    path: /etc/containerd
    state: directory

- name: config containerd
  command: containerd config default | sudo tee /etc/containerd/config.toml

- name: Enable containerd
  service:
    name: containerd
    enabled: yes

- name: Restart containerd
  service:
    name: containerd
    state: restarted